spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'false'
          lowerCaseServiceId: true
  application:
    name: gateway-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    gateway:
      enabled: 'true'
  
eureka:
  instance:
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
server:
  port: '8072'